---
driver:
  name: docker
  use_sudo: false
  socket: <%= ENV.fetch('DOCKER_HOST', 'unix:///var/run/docker.sock') %>
  provision_command: curl -L http://www.opscode.com/chef/install.sh | bash

provisioner:
  name: chef_zero
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
- name: ubuntu
  driver_config:
    image: ubuntu:14.04
    platform: ubuntu
- name: debian
  driver_config:
    image: debian:7.6
    platform: debian

suites:
- name: default
  run_list:
    - recipe[dop_base::default]
  attributes: {}